variables:
  SCHEME: "SplitPics"
  PROJECT: "-workspace SplitPics.xcworkspace"

before_script:
  - export LANG=en_US.UTF-8
  - mkdir artifacts
  - export ARCHIVEPATH=$(pwd)/artifacts/${SCHEME}.xcarchive
  - export EXPORTPATH=$(pwd)/artifacts/$CI_PROJECT_NAME-$CI_COMMIT_TAG

stages:
  - dev
  - release

dev:
  stage: dev
  only:
    - master
  script:
    - export CONFIGURATION="Debug"
    - xcodebuild clean ${PROJECT} -scheme ${SCHEME} -configuration ${CONFIGURATION}
    - pod install --no-repo-update
    - xcodebuild build ${PROJECT} -scheme ${SCHEME} -configuration ${CONFIGURATION} -allowProvisioningUpdates -quiet
    - xcodebuild clean ${PROJECT} -scheme ${SCHEME} -configuration ${CONFIGURATION}

release:
  stage: release
  only:
    - tags
  script:
    - export CONFIGURATION="Release"
    - xcodebuild clean ${PROJECT} -scheme ${SCHEME} -configuration ${CONFIGURATION}
    - pod install --no-repo-update
    - xcodebuild archive ${PROJECT} -scheme ${SCHEME} -configuration ${CONFIGURATION} -archivePath $ARCHIVEPATH -allowProvisioningUpdates -quiet
    - xcodebuild -exportArchive -allowProvisioningUpdates -exportOptionsPlist ExportOption.plist  -archivePath $ARCHIVEPATH -exportPath $EXPORTPATH
    - xcodebuild clean ${PROJECT} -scheme ${SCHEME} -configuration ${CONFIGURATION}
  artifacts:
    paths:
      - artifacts